// This file is automatically generated by Convex.
// It should not be edited manually.
// If you need to modify this file, please contact Convex support.

import type { ApiFromModules } from "convex/server"
import type * as admin from "../admin"
import type * as assessment_details from "../assessment-details"
import type * as assessments from "../assessments"
import type * as client_dashboard from "../client-dashboard"
import type * as communications from "../communications"
import type * as dashboard from "../dashboard"
import type * as domains from "../domains"
import type * as invintations from "../invintations"
import type * as member from "../member"
import type * as mutations from "../mutations"
import type * as notifications from "../notifications"
import type * as permissions from "../permissions"
import type * as pricing from "../pricing"
import type * as queries from "../queries"
import type * as roles from "../roles"
import type * as sessions from "../sessions"
import type * as tenant_users from "../tenant-users"
import type * as tenant from "../tenant"
import type * as tenants from "../tenants"
import type * as users from "../users"
import type * as vehicles from "../vehicles"
import type * as waitlist from "../waitlist"

/**
 * A type describing your Convex API.
 *
 * This type includes information about the arguments, return type, and
 * permissions for each query and mutation in your API.
 */
export type API = ApiFromModules<{
  admin: typeof admin
  "assessment-details": typeof assessment_details
  assessments: typeof assessments
  "client-dashboard": typeof client_dashboard
  communications: typeof communications
  dashboard: typeof dashboard
  domains: typeof domains
  invintations: typeof invintations
  member: typeof member
  mutations: typeof mutations
  notifications: typeof notifications
  permissions: typeof permissions
  pricing: typeof pricing
  queries: typeof queries
  roles: typeof roles
  sessions: typeof sessions
  "tenant-users": typeof tenant_users
  tenant: typeof tenant
  tenants: typeof tenants
  users: typeof users
  vehicles: typeof vehicles
  waitlist: typeof waitlist
}>

export declare const api: API

// Export query and mutation helpers for use in other files
export const query = {} as Record<string, any>
export const mutation = {} as Record<string, any>

// Add all query and mutation functions to the exported objects
Object.entries(api.query || {}).forEach(([name, fn]) => {
  query[name] = name
})

Object.entries(api.mutation || {}).forEach(([name, fn]) => {
  mutation[name] = name
})
